version: '3.8'
services:
  # サーバーコンテナの作成
  web:
    build: .
    # コンテナ名の指定 PJごとに変更
    container_name: front_pj_base
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/local/apache2/htdocs
